import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Project from '../components/project'

const Home: NextPage = () => {
  return (
    <div>
      <div className={styles.containerOuter + " " + styles.pseudo}>
      </div>
      <div className={styles.containerOuter + " " + styles.real}>
        <div className={styles.blackBg}>
        </div>
        <div className={styles.containerInner}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.splash}>
              <div className={styles.inner}>
                <h1>
                  Jess {' '}
                  Peter
                </h1>

                <div className={styles.titleInfo}>
                  <div className={styles.arrowDown}>
                  </div>
                  <div className={styles.detailInfo}>
                    <p>interaction design</p>
                    <p>+ data visualization</p>
                    <p>+ creative coding</p>
                    <p>+ everything below</p>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.projectList}>
              <Project 
              org= {"Thomson Reuters Labs"}
              title= {"Senior Designer"}
              info= {"Thomson Reuters Labs are the \“global reaching innovation arm\” of Thomson Reuters. I worked alongside multi-disciplinary teams on creating new features and powering up existing products with state-of-the-art data science techniques."}
              responsibilities={"Product design, user research, user experience design, data analysis, front-end development."}
              image= {"https://www.placecage.com/640/360"}
              years= {[2019, 2021]}/>

              <Project 
              org= {"Personal Project"}
              title= {"Goodwill Hunting"}
              info= {"I do a lot of personal projects to keep my skills sharp and investigate things that interest me. For Goodwill Hunting, I wanted to know what types of clothes are donated to Goodwill charity shops, and make some beautiful charts about my findings. This project made #1 on Hacker News. It's my nerdiest claim to fame."}
              responsibilities={"Visual design, data analysis, front-end development."}
              image= {"https://www.placecage.com/600/360"}
              years= {[2019]}/>

              <Project 
              org= {"Oslo School of Architecture and Design"}
              title= {"Master's Degree"}
              info= {"Thomson Reuters Labs are the \“global reaching innovation arm\” of Thomson Reuters. I worked alongside multi-disciplinary teams on creating new features and powering up existing products with state-of-the-art data science techniques."}
              responsibilities={"Product design, user research, user experience design, data analysis, front-end development."}
              image= {"https://www.placecage.com/640/360"}
              years= {[2019, 2021]}/>

              <Project 
              org= {"The Pudding"}
              title= {"Cover Matters"}
              info= {"Thomson Reuters Labs are the \“global reaching innovation arm\” of Thomson Reuters. I worked alongside multi-disciplinary teams on creating new features and powering up existing products with state-of-the-art data science techniques."}
              responsibilities={"Product design, user research, user experience design, data analysis, front-end development."}
              image= {"https://www.placecage.com/640/360"}
              years= {[2019, 2021]}/>

              <Project 
              org= {"The Globe and Mail"}
              title= {"Design and Front-end Dev Lead"}
              info= {"Thomson Reuters Labs are the \“global reaching innovation arm\” of Thomson Reuters. I worked alongside multi-disciplinary teams on creating new features and powering up existing products with state-of-the-art data science techniques."}
              responsibilities={"Product design, user research, user experience design, data analysis, front-end development."}
              image= {"https://www.placecage.com/640/360"}
              years= {[2019, 2021]}/>
            </div>
          </main>
        </div>
      </div>
    </div>
  )
}

export default Home
